version: '3.9'
services:
  app:
    image: "enoca-assignment:1.0"
    build:
      context: .
    ports:
      - 8085:8085
    environment:
     - "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}"
     - "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}"
     - "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}"
    networks:
      - app-network
    links:
      - db:enoca
    depends_on:
      - db
  db:
    image: mysql
    container_name: "db"
    ports:
      - 3306:3306
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}"
    networks:
      - app-network
    volumes:
      - db:/var/lib/mysql
networks:
  app-network:
volumes:
  db:
