version: '3.9'
services:
  app:
    image: enoca-assignment:1.0
    ports:
      - 8085:8085
    environment:
     - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/enoca"
     - "SPRING_DATASOURCE_USERNAME=root"
     - "SPRING_DATASOURCE_PASSWORD=123456"
    links:
      - db:enoca
    depends_on:
      - db
  db:
    image: mysql
    container_name: "db"
    ports:
      - 3306:3306
    environment:
      - "MYSQL_DATABASE=enoca"
      - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
